nodeLinker: node-modules
packageExtensions:
  "@storybook/addon-essentials@*":
    dependencies:
      "@storybook/addon-actions": "*"
      "@storybook/addon-backgrounds": "*"
      "@storybook/addon-controls": "*"
      "@storybook/addon-docs": "*"
      "@storybook/addon-measure": "*"
      "@storybook/addon-outline": "*"
      "@storybook/addon-toolbars": "*"
      "@storybook/addon-viewport": "*"
  "@storybook/addon-interactions@*":
    dependencies:
      "@storybook/global": "*"
      "@storybook/instrumenter": "*"
      "storybook": "*"
      "polished": "*"
